# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 🏗️ Build

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  actions: write
  contents: read
  packages: write

jobs:
  build:
    name: 🛠 Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: 🛑 Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.1
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: "https://npm.pkg.github.com"
        cache: 'yarn'
    - run: yarn
    - run: yarn build
    - uses: actions/upload-artifact@v4
      with:
        name: build-artifact-${{ matrix.node-version }}
        path: ./dist

    - name: 💾 Cache
      id: cache-build
      uses: actions/cache@v4
      with:
        path: ./dist
        key: ${{ github.sha }}
