name: 🚀 Publish

on:
  release:
    types: [created]
  workflow_dispatch:


permissions:
  actions: write
  contents: read
  packages: write

jobs:
  build:
    name: 🛠 Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: 🛑 Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.1
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: "https://npm.pkg.github.com"
        cache: 'yarn'
    - run: yarn
    - run: yarn build
    - uses: actions/upload-artifact@v4
      with:
        name: build-artifact-${{ matrix.node-version }}
        path: ./dist

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: "20.x"
  #         registry-url: https://npm.pkg.github.com/
  #         cache: 'yarn'
  #     - uses: actions/cache@v4
  #       id: cache-build
  #       with:
  #         path: ./dist
  #         key: ${{ github.sha }}
  #     - run: echo "@majortom327:registry=https://npm.pkg.github.com" >> .npmrc
  #     - run: yarn publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: build-artifact
  #         path: ./dist

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - uses: actions/cache@v4
        id: cache-build
        with:
          path: ./dist
          key: ${{ github.sha }}
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist
